# Generated by Django 3.1 on 2020-08-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='文章标题')),
                ('image', models.ImageField(upload_to='images')),
                ('introduction', models.CharField(max_length=200, verbose_name='文章简介')),
                ('content', models.CharField(max_length=2000, verbose_name='文章内容')),
                ('read_nums', models.IntegerField(default=0, verbose_name='阅读量')),
                ('category', models.CharField(default='文章类型', max_length=20, verbose_name='文章类型')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
