# Generated by Django 3.1 on 2020-08-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
    ]
