# Generated by Django 3.1 on 2020-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200806_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish'), (2, 'Delete')], default=0),
        ),
    ]
