# Generated by Django 3.1 on 2020-08-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200806_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='status',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
