# Generated by Django 3.1 on 2020-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200806_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
