# Generated by Django 3.1 on 2020-08-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200806_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='introduction',
            field=models.CharField(max_length=400, verbose_name='文章简介'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=300, verbose_name='文章标题'),
        ),
    ]
