# Generated by Django 3.1 on 2020-08-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200807_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='introduction',
            field=models.TextField(verbose_name='文章简介'),
        ),
    ]
